### ISSUE TITLE
Upload legit version to Modrinth

### ISSUE THREAD

**Issue by MicrocontrollersDev** [odtheking/Odin#132]
This is a request to upload the legit version of Odin to Modrinth (Modrinth doesn't allow cheats so only the legit version can be uploaded). Most major skyblock mods now have downloads available on Modrinth which allows people using Prism or Modrinth launcher to automatically update their mods, which would be very useful.

**Comment by odtheking** [comment]
Odin is planned to be uploaded to modrinth once it is stable and useable to avoid releasing a mod that isn't functional
