### ISSUE TITLE
Odin causing weird graphical issues

### ISSUE THREAD

**Issue by mandelmann** [odtheking/Odin#143]
I have these weird graphical issues when using the legit mod. When taking this picture I had no other mods in my mod folder and all odin features disabled.
![2024-12-24_22 18 43](https://github.com/user-attachments/assets/483c2ce5-ed47-45f2-9aa7-a218f3b89b45)
To clarify:
In the picture you can see entities rotated onto there heads and roatated around some midpoint. And this problem only occurs with other player around.
Hope you can help me,
Thanks in advance

**Comment by odtheking** [comment]
It is a problem with essential cosmetic rendering either enable the setting or update to latest essential version

**Comment by mandelmann** [comment]
thx fixed it

**Comment by mandelmann** [comment]
thx a lot, fixed it
