### ISSUE TITLE
Inconsistencies in module and setting descriptions.

### ISSUE THREAD

**Issue by freebonsai** [odtheking/Odin#96]
- Some descriptions start with uppercase while some start with lowercase.
- Some descriptions are missing commas.
- Some modules/ settings are missing descriptions entirely.
- Some descriptions have typos, or are worded incorrectly.
- Some descriptions have inconsistent or unnatural wording.

**Comment by odtheking** [comment]
All module and settings have descriptions
All descriptions start with a capital letter and end with a dot
More than that is not possible for me
